export const CHANGE_INPUTS = 'CHANGE_INPUTS';
export const LOAD_CURRENCY_LIST_REQUEST = 'LOAD_CURRENCY_LIST_REQUEST';
export const LOAD_CURRENCY_LIST_SUCCESS = 'LOAD_CURRENCY_LIST_SUCCESS';
export const LOAD_FIXRATE_REQUEST = 'LOAD_FIXRATE_REQUEST';
export const LOAD_FIXRATE_SUCCESS = 'LOAD_FIXRATE_SUCCESS';
